<a href="https://colab.research.google.com/github/Hubert246/Data-Science-Bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Podstawy

In [ ]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x.ndim

(2,)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size

2

In [ ]:
x.shape

(2,)

## Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(4, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype=int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=20, stop=0, step=-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
np.arange(start=0, stop=10, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25,
       3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 ,
       3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35,
       4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 ,
       4.95, 5.  , 5.05, 5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 , 5.45,
       5.5 , 5.55, 5.6 , 5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95, 6.  ,
       6.05, 6.1 , 6.15, 6.2 , 6.25, 6.3 , 6.35, 6.4 , 6.45, 6.5 , 6.55,
       6.6 , 6.65, 6.7 , 6.75, 6.8 , 6.85, 6.9 , 6.95, 7.  , 7.05, 7.1 ,
       7.15, 7.2 , 7.25, 7.3 , 7.35, 7.4 , 7.45, 7.

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podstawowe operacje na tablicach

In [ ]:
import numpy as np
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A - B

array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2 * A

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X@Y

array([[  3,   6],
       [-12,   0]])

# GENEROWANIE LICZB PSEUDOLOSOWYCH

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

0.08014428826386436

In [ ]:
np.random.randn(10)

array([-0.77922009, -0.09602995, -1.30964256,  0.56717551, -0.07168474,
       -2.10169251, -0.90649405,  1.196783  , -0.458428  , -1.26005193])

In [ ]:
np.random.randn(10, 4)

array([[-0.61184924,  0.93957608,  0.00308801, -0.969046  ],
       [ 1.06998516, -1.38442161,  0.40180717, -1.10085679],
       [ 0.38547271,  1.07580663,  2.33466409,  0.3419499 ],
       [-0.41522603, -0.33861771, -0.144233  ,  0.16932946],
       [-0.82158488,  0.73349064,  0.3290528 ,  0.14282169],
       [-0.05253659, -0.34201103, -0.85837605,  0.77744059],
       [ 0.13186538,  1.25737568,  0.14803142,  0.59153677],
       [-0.07669113, -0.26223987,  0.98325918, -1.12629498],
       [ 0.53112381, -0.72089008,  0.13218299, -1.0385423 ],
       [ 0.23704484, -1.34544627, -0.2737169 , -1.64018911]])

In [ ]:
np.random.rand()

0.7169997556473848

In [ ]:
np.random.rand(10, 2)

array([[0.56294015, 0.42250194],
       [0.39046834, 0.94004884],
       [0.87767699, 0.88543093],
       [0.15798759, 0.04174267],
       [0.63440722, 0.91035333],
       [0.8784242 , 0.22078138],
       [0.6882701 , 0.97838749],
       [0.72698156, 0.7517401 ],
       [0.76848991, 0.38799961],
       [0.72032202, 0.87096526]])

In [ ]:
np.random.randint(10)

0

In [ ]:
np.random.randint(low=10, high=101)

32

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([ 37,  47,  76,  48,  78, 100,  16,  65,  91,  16])

In [ ]:
np.random.choice([4, 2, 1, 4])

2

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([1, 0, 8, 9, 3, 2, 6, 5, 7, 4])

# PODSTAWOWE FUNKCJE W NUMPY

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])

True

In [ ]:
np.all([2, 3, 0])

False

In [ ]:
np.any([1, 0, 0])

True

In [ ]:
np.any([0, 0, 0])

False

In [ ]:
A = np.random.rand(5)
A

array([0.6497254 , 0.01904546, 0.18400277, 0.84619484, 0.27165415])

In [ ]:
np.argmax(A)

3

In [ ]:
A[np.argmax(A)]

0.8461948448919809

In [ ]:
np.argmin(A)

1

In [ ]:
np.argsort(A)

array([1, 2, 4, 0, 3])

In [ ]:
np.max(A)

0.8461948448919809

In [ ]:
np.min(A)

0.019045464918425847

In [ ]:
np.mean(A)

0.3941245260887598

# INDEKSOWANIE, WYCINANIE


In [46]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
A[2]

2

In [48]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [49]:
A[:2]

array([0, 1])

In [50]:
A[[0, 2]]

array([0, 2])

In [52]:
A[19]

19

In [53]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
A[:, 1]

array([ 1,  6, 11, 16])

In [55]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [56]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# ITERACJA PO TABLICACH

In [57]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [59]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [60]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


# ZMIANA ROZMIARU TABLIC

In [61]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# MASKI LOGICZNE

In [65]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [68]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [70]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])