<a href="https://colab.research.google.com/github/Hubert246/Data-Science-Bootcamp/blob/main/01_wprowadzenie.02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

4.123105625617661

In [6]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2) #dlugosc wektora

19.209372712298546

In [8]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q) #odleglosc punktow

5.0

In [9]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

In [10]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y) #mnozenie macierzy

In [12]:
print(Z)

[[ 2]
 [-6]]


In [14]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A) #wyznacznik macierzy

9.999999999999998

In [15]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A) #slad macierzy - suma elementow na przekatnej

5

In [16]:
np.eye(5, dtype='int') #macierz jednostkowa

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
A


array([[ 2,  4],
       [-1,  3]])

In [19]:
B = np.linalg.inv(A) #macierz odwrotna
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [20]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [21]:
np.transpose(A) #macierz transponowana

array([[ 2, -1],
       [ 4,  3]])

In [22]:
A.T #macierz transponowana

array([[ 2, -1],
       [ 4,  3]])

In [24]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [26]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [27]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]
